[package]
name = "elden-analyzer-kernel"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
num-rational.workspace = true
thiserror.workspace = true
