#!/bin/bash

level1=""
level2=""

while read -r line; do
    case "${line}" in
    "") ;;
    "# "*)
        level1="${line:2}"
        level2=""
        ;;
    "## "*)
        level2="${line:3}"
        ;;
    *)
        echo -e "${level1}\t${level2}\t${line}"
        ;;
    esac
done
