name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  ci-complete:
    needs: ci
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - run: |
          if ${{ needs.ci.result == 'success' }}; then
            echo "CI succeeded"
            exit 0
          else
            echo "CI failed"
            exit 1
          fi
